### ISSUE TITLE
Error when attempting to use Kanta

### ISSUE THREAD

**Issue by j70k** [unifiton/kantanni#10]
When attempting to use Kanta, an error is thrown.

```shell
SyntaxError: Unexpected strict mode reserved word
    at wrapSafe (internal/modules/cjs/loader.js:1001:16)
    at Module._compile (internal/modules/cjs/loader.js:1049:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:14)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (module.js:23:17)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
```

**Comment by j70k** [comment]
This is really useless and I'm basically talking to myself but I don't mind

**Comment by j70k** [comment]
fixed with this PR
